version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: user  
      MYSQL_DATABASE: blogit
    volumes:
      - ./mysql:/var/lib/mysql  
  
  adminblogit:
    build:
      context: ./adminblogit  
    environment:
      - CREATE_TABLE=${CREATE_TABLE:-FALSE}  
    depends_on:
      - db
    ports:
      - "80:80"  
